Makefile
Coq on Windows generally does not support paths like `/cygdrive/d/Documents/GitHub/bedrock2/deps/coqutil/src/Datatypes/HList.v`.  These are the sorts of paths generated by `pwd` / `find` under cygwin, unless you run the initial path through `cygpath -m` (`-m` for mixed, which makes it use forward slashes).  We pipe stderr to `/dev/null` and fallback to `pwd` on platforms where `cygpath` is not in path (i.e., non-windows platforms).
=> Fix build on Windows

src/Word/Properties.v
See https://github.com/coq/coq/issues/10474 and
https://github.com/coq/coq/issues/10480
This is in preparation for coq/coq#10476 which fixes these two bugs, and is backward compatible (tested on Coq's master).
=> Avoid relying on `Export` bugs

.gitignore
Empty vok files are now also generated during normal compilation (in addition to the empty vos files); see coq/coq#11075.
=> Update gitignore after coq/coq#11075

src/coqutil/Datatypes/PropSet.v
Similar to #27, this PR upstreams generalizable facts about sets that I needed while developing fiat-crypto's bedrock2 backend.
Most lemmas are pretty basic; probably the more controversial elements added are a) RelationClasses and Proper instances for all the set operations and b) some lemmas that rely on decidable equality of set elements.
=> New set lemmas

src/coqutil/Datatypes/List.v, src/coqutil/Map/Interface.v, src/coqutil/Map/MapKeys.v, src/coqutil/Map/OfFunc.v, src/coqutil/Map/OfListWord.v, src/coqutil/Map/Properties.v
Currently implemented:
- lists as maps with nat keys
- lists as maps with nat keys with some nat offset
- lists as maps with Z keys
- lists as maps with Z keys with some Z offset
- lists as maps with word keys
- lists as maps with word keys with some word offset
The main advantage of this construction is that it has a complete `get` law for the resulting maps, allowing to prove integer bounds on an address that was found to be within the constructed memory.
Please skim the definitions to check that they match your understanding of what we want in coqutil.
=> Encoding functions with finite support as maps

src/coqutil/Macros/symmetry.v
This ensures that grepping the source for admits comes back clean.
=> Avoid using admit even in tests

src/coqutil/Z/ZLib.v, src/coqutil/Z/div_mod_to_equations.v
This PR makes ZLib.v and div_mod_to_equations.v work with https://github.com/coq/coq/pull/14086 in a backwards compatible manner.
=> Future proof ZLib.v and div_mod_to_equations.v

Makefile, src/coqutil/Z/bitblast.v
Fiat-Crypto uses Z.bitblast, so it needs to be compatible back to 8.11.
The other files that don't build with earlier versions of Coq are now
excluded.
Fixes #57 (once the auto-update runs)
=> Restore compatibility with fiat-crypto

src/coqutil/Word/LittleEndian.v
This was discovered while preparing https://github.com/coq/coq/pull/15760
=> Properly deprecate combine and split

src/coqutil/Datatypes/List.v
Replace all uses of deprecated `Minus.minus_plus`, `Zdiv.div_Zdiv`, `Zdiv.mod_Zmod` (coq/coq#16920).
=> Adapt to coq/coq#16920 (and remove uses of deprecated Minus.minus_plus)

src/coqutil/Datatypes/Result.v
Add the recommended function to improve unwrapping an evaluated success in mit-plv/bedrock2/pull/335.
=> Add 'of_Success' function to unwrap evaluated results

src/coqutil/Word/Naive.v
More robust given use of Unset Universe Minimization ToSet, cf https://github.com/coq/coq/pull/17810 and related
=> Use : Set explicitly when needed

src/coqutil/Datatypes/RecordSetters.v, src/coqutil/Datatypes/RecordSettersUsingExistingGetters.v, src/coqutil/Ltac2Lib/List.v, src/coqutil/Ltac2Lib/String.v, src/coqutil/Tactics/fold_hyps.v
Should be backwards compatible (by vendoring the new definition until backward compat is dropped)
=> Adapt to coq/coq#18197 (List and Array fold argument order change)

Makefile
This works even if `default_goal` (or `.DEFAULT_GOAL`) is a file that exists, and even if `test` is not `PHONY`
=> Use a more standard way of setting the default goal

Makefile
This way we can support people who are silly and name directories things like `\n` or `%s`
=> Makefile: More robust printf invocation

src/coqutil/Word/Properties.v
`word.or_assoc`, `word.or_0_l`, and `word.or_0_r` are used in the crit-bit tree study in LiveVerif. I also added `word.and_assoc` and `word.xor_assoc` for completeness.
=> A few associativity and absorption lemmas for `word.and`, `word.or`, and `word.xor`

src/coqutil/Lift1Prop.v, src/coqutil/Map/Separation.v, src/coqutil/Map/SeparationLogic.v
I'd like to be able to reason about separation logic in Coq projects without depending on the entirety of bedrock2 -- it would be nice for me (and maybe others!) if the basic logic moved from bedrock2 to coqutil.
This is just a straight-up copy of the basic definitions from bedrock2, and after it's merged I have a follow-up PR for bedrock2 that would remove them and reference these instead. I didn't change any code except for the paths where these files import each other.
=> Copy separation-logic definitions from bedrock2 to coqutil.

src/coqutil/Datatypes/Option.v, src/coqutil/Eqb.v, src/coqutil/InversionRewrite.v, src/coqutil/PropRewrite.v, src/coqutil/Tactics/case_match.v, src/coqutil/Tactics/safe_invert.v
Adds an Eqb class for types with boolean equality, a set of lemmas gathered into a rewrite database for greedy proposition simplification, another rewrite database for datatype inversion, and some generic tactics for inversion and case analysis.
=> Add Eqb class, rewrite dbs, and some tactics from Pyrosome

Makefile, src/coqutil/Datatypes/Option.v, src/coqutil/Eqb.v, src/coqutil/InversionRewrite.v
Perennial builds coqutil with a _CoqProject that uses `-Q coqutil/src coqutil` rather than `-R`, which makes these `From coqutil` qualifiers required.
We could change Perennial but I think these are good style anyway and this is the first time this has been a problem.
=> Add From coqutil to imports

src/coqutil/Map/SeparationLogic.v, src/coqutil/Map/SeparationLogic_test.v
cancel wasn't removing syntactically equal clauses from lists of seps when using impl1 instead of iff1. Add a new tactic to remove those and a test for it.
=> cancel: remove equal clauses for impl1
